spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: first_api
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      # redis:
      # time-to-live: 60000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: SoloPostgres1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true