-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
<<<<<<< HEAD
                              "name" varchar NOT NULL,
                              last_name varchar NOT NULL,
                              email varchar NOT NULL,
                              birthdate date NULL,
                              created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              "uuid" uuid NULL
);

-- Permissions

ALTER TABLE public.users OWNER TO postgres;
GRANT ALL ON TABLE public.users TO postgres;

=======
                              first_name varchar NOT NULL,
                              last_name varchar NOT NULL,
                              email varchar NOT NULL,
                              birthdate date NULL,
                              "uuid" uuid NULL,
                              created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              CONSTRAINT users_pk PRIMARY KEY (id)
);
>>>>>>> c572bc0 (primera api)
